export const types = {
 STUDENT_LOGIN: "STUDENT_LOGIN",
 INSTRUCTOR_LOGIN: "INSTRUCTOR_LOGIN",
 LOGOUT_USER: "LOGOUT_USER",
 PLAYLIST_ID: "PLAYLIST_ID",
 PLAYLIST_ITEMS: "PLAYLIST_ITEMS",
 REMOVE_PLAYLIST: "REMOVE_PLAYLIST",
 USERS_DATA: "USERS_DATA"
};
